# Generated by Django 2.2.1 on 2019-09-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Address',
            new_name='Author_Name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Username',
            new_name='Book_Id',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Email',
            new_name='Book_Name',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Gender',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Name',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='books',
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='books',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='books',
            name='Phone_number',
        ),
    ]
