# Generated by Django 2.2.1 on 2019-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190920_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksdetails',
            fields=[
                ('Book_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
