# Generated by Django 2.2.1 on 2019-09-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190921_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booksdetails',
            new_name='bookdetails',
        ),
    ]
