# Generated by Django 2.2.1 on 2019-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190921_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='Book_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
