# Generated by Django 2.2.1 on 2019-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190923_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='Book_Status',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
