# Generated by Django 2.2.5 on 2019-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookdetails_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='Book_Status',
            field=models.CharField(default='Not-issued', max_length=50),
        ),
    ]
