# Generated by Django 2.2.5 on 2019-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190923_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='rqstbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Request_date', models.DateField(max_length=50)),
                ('Return_date', models.DateField(max_length=50)),
            ],
        ),
    ]
