# Generated by Django 2.2.5 on 2019-11-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20191107_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rqstbook',
            old_name='Username',
            new_name='Name',
        ),
    ]
