# Generated by Django 2.2.1 on 2019-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='readers',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
    ]
